# RPC / P2P node: larger network buffers
# P2P more stable, lower RPC latency
net.core.rmem_max = 268435456
net.core.wmem_max = 268435456
net.core.netdev_max_backlog = 250000
net.ipv4.tcp_max_syn_backlog = 8192
