# op-node 使用公共 L1 端点（无本地 L1 节点时）
# 用法: docker compose -f docker-compose-op-reth-home.yml -f docker-compose-op-reth-home-l1-public.yml up -d op-node

services:
  op-node:
    command:
      - "--network=base-mainnet"
      - "--l2=ws://host.docker.internal:8552"
      - "--l2.jwt-secret=/jwt/jwt.hex"
      - "--l2.enginekind=reth"
      - "--l1=https://ethereum-rpc.publicnode.com"
      - "--l1.beacon=https://ethereum-beacon-api.publicnode.com"
      - "--l1.max-concurrency=100"
      - "--l1.cache-size=2500"
      - "--l1.http-poll-interval=2s"
      - "--l2.engine-rpc-timeout=60s"
      - "--rpc.addr=0.0.0.0"
      - "--rpc.port=8549"
      - "--p2p.priv.path=/data/opnode_p2p_priv.txt"
      - "--p2p.discovery.path=/data/opnode_discovery_db"
      - "--p2p.peerstore.path=/data/opnode_peerstore_db"
      - "--p2p.listen.tcp=9222"
      - "--p2p.listen.udp=9222"
      - "--p2p.advertise.ip=38.102.126.30"
      - "--p2p.advertise.tcp=9222"
      - "--p2p.advertise.udp=9222"
      - "--p2p.bootnodes=enr:-J24QNz9lbrKbN4iSmmjtnr7SjUMk4zB7f1krHZcTZx-JRKZd0kA2gjufUROD6T3sOWDVDnFJRvqBBo62zuF-hYCohOGAYiOoEyEgmlkgnY0gmlwhAPniryHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQKNVFlCxh_B-716tTs-h1vMzZkSs1FTu_OYTNjgufplG4N0Y3CCJAaDdWRwgiQG,enr:-J24QH-f1wt99sfpHy4c0QJM-NfmsIfmlLAMMcgZCUEgKG_BBYFc6FwYgaMJMQN5dsRBJApIok0jFn-9CS842lGpLmqGAYiOoDRAgmlkgnY0gmlwhLhIgb2Hb3BzdGFja4OFQgCJc2VjcDI1NmsxoQJ9FTIv8B9myn1MWaC_2lJ-sMoeCDkusCsk4BYHjjCq04N0Y3CCJAaDdWRwgiQG,enr:-J24QDXyyxvQYsd0yfsN0cRr1lZ1N11zGTplMNlW4xNEc7LkPXh0NAJ9iSOVdRO95GPYAIc6xmyoCCG6_0JxdL3a0zaGAYiOoAjFgmlkgnY0gmlwhAPckbGHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQJwoS7tzwxqXSyFL7g0JM-KWVbgvjfB8JA__T7yY_cYboN0Y3CCJAaDdWRwgiQG,enr:-J24QHmGyBwUZXIcsGYMaUqGGSl4CFdx9Tozu-vQCn5bHIQbR7On7dZbU61vYvfrJr30t0iahSqhc64J46MnUO2JvQaGAYiOoCKKgmlkgnY0gmlwhAPnCzSHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQINc4fSijfbNIiGhcgvwjsjxVFJHUstK9L1T8OTKUjgloN0Y3CCJAaDdWRwgiQG,enr:-J24QG3ypT4xSu0gjb5PABCmVxZqBjVw9ca7pvsI8jl4KATYAnxBmfkaIuEqy9sKvDHKuNCsy57WwK9wTt2aQgcaDDyGAYiOoGAXgmlkgnY0gmlwhDbGmZaHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQIeAK_--tcLEiu7HvoUlbV52MspE0uCocsx1f_rYvRenIN0Y3CCJAaDdWRwgiQG"
      - "--verifier.l1-confs=4"
      - "--rollup.load-protocol-versions=true"
      - "--l1.beacon.fetch-all-sidecars=true"
      - "--l1.trustrpc=false"
      - "--syncmode=execution-layer"
