/**
 * 合约地址 - 从全局 config/contract-addresses.ts 导入，禁止在此定义。
 */
export {
  BASE_AA_FACTORY,
  BASE_CARD_FACTORY,
  BASE_CCSA_CARD_ADDRESS,
  BASE_TREASURY,
  BEAMIO_USER_CARD_ASSET_ADDRESS,
  PURCHASING_CARD_METADATA_ADDRESS,
  USDC_BASE,
  CONET_BUNIT_AIRDROP_ADDRESS,
  BEAMIO_INDEXER_DIAMOND,
  MERCHANT_POS_MANAGEMENT_CONET,
  BASE_MAINNET_FACTORIES,
  CONTRACT_ADDRESSES,
} from '../../../config/contract-addresses'
